# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 22, host: 2202, id: 'ssh'
  config.vm.network "forwarded_port", guest: 3306, host: 33062
  config.vm.network "forwarded_port", guest: 8055, host: 8055
  config.ssh.forward_agent = true
  config.vm.provider "virtualbox" do |vb|
    vb.name = "p4-compiler-fuzzer-dev"
    vb.memory = "8192"
    vb.cpus = 4
  end
  config.vm.hostname = "p4-compiler-fuzzer-dev"
  config.vm.provision "shell", path: "root-bootstrap.sh"
  config.vm.provision "shell", privileged: false, path: "user-bootstrap.sh"
  config.vm.synced_folder "../src/", "/home/p4-compiler-fuzzer/p4-compiler-fuzzer/src", :owner => "p4-compiler-fuzzer"
  config.vm.synced_folder "../sql/", "/home/p4-compiler-fuzzer/p4-compiler-fuzzer/sql", :owner => "p4-compiler-fuzzer"
end